name: Build docs

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call_docs_workflow_cicd:
    name: Call Docs Workflow
    uses: ASU-CS-Research/OrganizationalWorkflows/.github/workflows/docs.yml@main
#    with:
#      api_static_docs_path: "./docs/api/"  # Uncomment if you have API swagger documentation to upload.
    secrets:
      CAMPELLCL_APPMAIS_SSH_PRIVATE_KEY_PEM: ${{ secrets.CAMPELLCL_APPMAIS_SSH_PRIVATE_KEY_PEM }}
